name: Vercel Dev Deployment
env:
  VERCEL_ORG_ID: team_H0VqfkPq57f7aPgkORbzAbIC
  VERCEL_PROJECT_ID: prj_9owz1BasSUAy4ICsGl1JMY8PJfhn
on:
  push:
    branches:
      - master

jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=Fm5UcMSLkWy464B1e1a6Q3SI
      - name: Build Project Artifacts
        run: vercel build --token=Fm5UcMSLkWy464B1e1a6Q3SI
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=Fm5UcMSLkWy464B1e1a6Q3SI